### ISSUE TITLE
Could you create a release for MacOSX?

### ISSUE THREAD

**Issue by 030** [shoenig/bcrypt-tool#5]

**Comment by epicsoft-de** [comment]
If you have a Docker you can use this image: https://hub.docker.com/r/epicsoft/bcrypt

**Comment by shoenig** [comment]
I would like to publish `bcyrpt-tool` as a formula in homebrew, but it does not yet meet their minimum criteria for inclusion 

> GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)

Which is kind of unfortunate, because I can see a few hundred people have it installed as an Ubuntu Snap alone :man_shrugging:

**Comment by shoenig** [comment]
I finally got around to setting up goreleaser for this project; pre-compiled binaries are now available on the [releases](https://github.com/shoenig/bcrypt-tool/releases) page
